# Generated by Django 2.2.24 on 2021-07-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0003_shop_time_cloae_sunday1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='time_cloae_sunday1',
            new_name='time_close_sunday1',
        ),
    ]
