# Generated by Django 2.2.24 on 2021-07-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLogin', '0007_auto_20210718_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='is_holiday_sunday',
            field=models.BooleanField(default='False', help_text='sunday', verbose_name='日曜日'),
        ),
    ]
