# Generated by Django 2.2.24 on 2021-07-16 15:59

import UserLogin.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('shop_number', models.PositiveSmallIntegerField(default=0, verbose_name='店舗ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('first_name_representative', models.CharField(blank=True, help_text='代表者の方の「名」', max_length=30, verbose_name='代表者「名」')),
                ('last_name_representative', models.CharField(blank=True, help_text='代表者の方の「姓」', max_length=30, verbose_name='代表者「姓」')),
                ('first_name_representative_kana', models.CharField(blank=True, help_text='代表者の方の「メイ」(フリガナ)', max_length=30, verbose_name='代表者「メイ」')),
                ('last_name_representative_kana', models.CharField(blank=True, help_text='代表者の方の「セイ」(フリガナ)', max_length=30, verbose_name='代表者「セイ」')),
                ('first_name_manager', models.CharField(blank=True, help_text='管理者の方の「名」', max_length=30, verbose_name='管理者「名」')),
                ('last_name_manager', models.CharField(blank=True, help_text='管理者の方の「姓」', max_length=30, verbose_name='管理者「姓」')),
                ('first_name_manager_kana', models.CharField(blank=True, help_text='管理者の方の「メイ」(フリガナ)', max_length=30, verbose_name='管理者「メイ」')),
                ('last_name_manager_kana', models.CharField(blank=True, help_text='管理者の方の「セイ」(フリガナ)', max_length=30, verbose_name='管理者「セイ」')),
                ('tel', models.CharField(blank=True, max_length=15, verbose_name='電話番号')),
                ('remarks', models.TextField(blank=True, max_length=150, verbose_name='備考')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '会員',
                'verbose_name_plural': '会員',
            },
            managers=[
                ('objects', UserLogin.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='SHOP', max_length=20, verbose_name='店名')),
                ('shop_name_kana', models.CharField(default='ショップ', max_length=30, verbose_name='テンメイ')),
                ('manager_name', models.CharField(default='CHIEF', max_length=15, verbose_name='管理者')),
                ('email', models.EmailField(max_length=255, verbose_name='お客様用メールアドレス')),
                ('tel_shop', models.CharField(blank=True, max_length=15, verbose_name='電話番号')),
                ('website', models.CharField(default='http://www.', max_length=100, verbose_name='サイトURL')),
                ('zip_code', models.CharField(blank=True, max_length=8, verbose_name='郵便番号')),
                ('address1', models.CharField(blank=True, max_length=40, verbose_name='都道府県')),
                ('address2', models.CharField(blank=True, max_length=40, verbose_name='市区町村')),
                ('address3', models.CharField(blank=True, max_length=40, verbose_name='丁目')),
                ('address4', models.CharField(blank=True, max_length=40, verbose_name='番地以降')),
                ('address5', models.CharField(blank=True, max_length=40, verbose_name='建物名・部屋番号等')),
                ('station1', models.CharField(blank=True, max_length=15, verbose_name='付近の駅・バス停１')),
                ('station1_time', models.PositiveSmallIntegerField(default=0, verbose_name='駅・バス停１からの所要時間')),
                ('station2', models.CharField(blank=True, max_length=15, verbose_name='付近の駅・バス停２')),
                ('station2_time', models.PositiveSmallIntegerField(default=0, verbose_name='駅・バス停２からの所要時間')),
                ('station3', models.CharField(blank=True, max_length=15, verbose_name='付近の駅・バス停３')),
                ('station3_time', models.PositiveSmallIntegerField(default=0, verbose_name='駅・バス停３からの所要時間')),
                ('is_holiday_sunday', models.BooleanField(default='False', verbose_name='日曜日')),
                ('is_holiday_monday', models.BooleanField(default='False', verbose_name='月曜日')),
                ('is_holiday_tuesday', models.BooleanField(default='False', verbose_name='火曜日')),
                ('is_holiday_wednesday', models.BooleanField(default='False', verbose_name='水曜日')),
                ('is_holiday_thursday', models.BooleanField(default='False', verbose_name='木曜日')),
                ('is_holiday_friday', models.BooleanField(default='False', verbose_name='金曜日')),
                ('is_holiday_saturday', models.BooleanField(default='False', verbose_name='土曜日')),
                ('point', models.IntegerField(default=0, verbose_name='店舗ID')),
                ('remarks_shop', models.TextField(blank=True, max_length=150, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_account', models.ForeignKey(null=True, on_delete='models.DO_NOTHING', related_name='ManagerAccount', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='管理者アカウント')),
            ],
            options={
                'verbose_name': '店舗情報',
                'verbose_name_plural': '店舗情報',
            },
        ),
    ]
